on:
  push:
    tags:
      - 'v*'
name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Packaged Extension Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'account_switcher_extension.zip'
          exclusions: '*.git* *.github* .gitignore'
